#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then run 'sh' with that shell as the shell's first argument
#       (e.g., 'sh my_script.sh').
#
#       If you do not have a compliant shell, you can instead run the script
#       with a compliant shell in a Docker container or in a virtual machine.
#
#   (2) The script only works with Gradle's distribution zip (the script will
#       unpack it automatically).
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$(ls -ld "$app_path")
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

APP_HOME=$(cd "${APP_HOME:-./}" && pwd -P) || exit

APP_BASE_NAME=${0##*/}

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$(uname)" in
  CYGWIN* )
    cygwin=true
    ;;
  Darwin* )
    darwin=true
    ;;
  MSYS* | MINGW* )
    msys=true
    ;;
  NONSTOP* )
    nonstop=true
    ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      max*)
        MAX_FD=$(ulimit -n -H) || warn "Could not query maximum file descriptor limit"
    esac
    case $MAX_FD in  #(
      '' | soft) :;; #(
      *)
        ulimit -n "$MAX_FD" || warn "Could not set maximum file descriptor limit to $MAX_FD"
    esac
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if dedicated module path)
#   * --module-path entries (only if SMF)
#   * and any other arguments

# For Gradle, the main class is 'org.gradle.wrapper.GradleWrapperMain'.
# The gradle wrapper jar will have the main class embedded in its manifest, but
# we should ensure the classpath includes only the wrapper jar and not any other
# local jars, which may not be wanted.
#
# For Cygwin, the paths are normalized by removing // and reformatting /cygdrive/-
# or /mnt/c/ paths.

# Convert any POSIX path to a Windows path.
if $cygwin ; then
    APP_HOME=$(cygpath --path --mixed "$APP_HOME")
    CLASSPATH=$(cygpath --path --mixed "$CLASSPATH")
    JAVACMD=$(cygpath --unix "$JAVACMD")

    # Now convert any arguments from Unix to Windows style.
    # For Cygwin, we need to retain the original quoting for some arguments (e.g. --module-path).
    # We also need to be careful to not treat '--module-path' as a Java option and also
    # not remove the '='.
    # For some reason, we are also splitting on spaces, but that seems to be a default.
    # We'll keep the original quoting.
    originalArguments="$@"
    set -- "$originalArguments"
fi

# Collect all arguments for the java command;
#   * $DEFAULT_JVM_OPTS, $JAVA_OPTS, and $GRADLE_OPTS can contain fragments of
#     shell script including quotes and variable substitutions, so put them in
#     double quotes to make sure that they get re-expanded; and
#   * put everything else in double quotes as well to account for spaces in paths.
set -- \
        "-Dorg.gradle.appname=$APP_BASE_NAME" \
        -classpath "$CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"

# Stop when "xargs" is not available.
if ! command -v xargs >/dev/null 2>&1
then
    die "xargs is not available"
fi

# Use "xargs" to parse quoted args.
#
# With -n1 it outputs one arg per line, with the quotes and backslashes removed.
#
# In Bash we could simply go:
#   readarray ARGS < <( xargs -n1 <<<"$var" ) &&
#   set -- "${ARGS[@]}" "$@"
#
# but POSIX script has no readarray, so instead we use a loop to append to the
# array.
# Using an array is faster than using 'set -- $(xargs ...)' which would spawn
# a subshell for each argument.
#
# This approach is also faster than using 'xargs -0' and then 'set --' because
# POSIX doesn't allow 'read -s' or 'read -0'.

# Use the shell's own 'read' which splits on spaces (IFS) by default.
# The args are unquoted in this environment, which is what we expect.
#
# Start with an empty array and append all args to it.
ARGS=()
while IFS= read -r line; do
    # Supporting newlines with a trailing newline in the string is possible
    # by leaving IFS as '\n' (default) and then stripping the trailing newline
    # from the captured string.
    # The trailing newline is given up because when a string is captured,
    # it includes the newline. This is usually desired.
    # However, when IFS is set to " \n", a word that only contains newline
    # will not be split, which is the desired behavior for Java arguments
    # that are intended to contain a newline.
    # `xargs -n1` will capture the newline and then the 'read' command will split at
    # the newline with IFS set to " \n" (the default when unspecified).
    #
    # shellcheck disable=SC2086
    set -- $line
    for arg in "$@"; do
        ARGS[${#ARGS[@]}]="$arg"
    done
done < <( xargs -n1 <<<"$( printf '%s\n' "$*" )" )

# Restore the positional arguments.
set -- "${ARGS[@]}"

# Execute Gradle
exec "$JAVACMD" "$@"